// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://onfjjmnzqgtimmxfhgmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9uZmpqbW56cWd0aW1teGZoZ21iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3ODkwNTQsImV4cCI6MjA2OTM2NTA1NH0.7ystgEvOhjWotyFxOgP2Cx3hOgjv8OnBCNTkNX39y0k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});